const Sector = require('../models/Sector');
const { getAllSectors, createSector, updateSector } = require('../utils/sectorStorage');
const { normalizeSectorRecord, getSectorById } = require('../controllers/sectorsController');
const { v4: uuidv4 } = require('uuid');

module.exports = async (fastify) => {
  // GET /sectors - List all sectors
  fastify.get('/', async (request, reply) => {
    try {
      const sectors = await getAllSectors();
      // Normalize all sectors to ensure sectorSymbol is included
      const normalizedSectors = sectors.map(sector => normalizeSectorRecord(sector));
      return reply.status(200).send(normalizedSectors);
    } catch (error) {
      return reply.status(500).send({
        error: error.message
      });
    }
  });

  // GET /sectors/:id - Get a single sector by ID
  fastify.get('/:id', async (request, reply) => {
    try {
      const { id } = request.params;
      const sector = await getSectorById(id);
      
      if (!sector) {
        return reply.status(404).send({
          error: 'Sector not found'
        });
      }
      
      return reply.status(200).send(sector);
    } catch (error) {
      return reply.status(500).send({
        error: error.message
      });
    }
  });

  // POST /sectors - Create a sector
  fastify.post('/', async (request, reply) => {
    try {
      const { name, sectorName, symbol, sectorSymbol, description, agents, performance } = request.body || {};

      // Extract sectorName and sectorSymbol from either field name
      const finalSectorName = (sectorName || name || '').trim();
      const finalSectorSymbol = (sectorSymbol || symbol || '').trim();

      // Create sector using the model
      const sector = new Sector({
        name: finalSectorName,
        description: description || '',
        agents: agents || [],
        performance: performance || {}
      });

      // Save to storage with sectorName and sectorSymbol
      const sectorData = {
        ...sector.toJSON(),
        sectorName: finalSectorName,
        sectorSymbol: finalSectorSymbol
      };
      const savedSector = await createSector(sectorData);

      // Auto-create manager agent
      const managerAgent = {
        id: uuidv4(),
        type: 'manager',
        name: 'Manager',
        description: 'Autogenerated manager agent for sector.',
        confidence: 0,
        role: 'manager',
        createdAt: Date.now()
      };

      // Add manager agent to sector's agents array
      const updatedAgents = [...(savedSector.agents || []), managerAgent];

      // Update sector with manager agent, preserving sectorName and sectorSymbol
      const updatedSector = await updateSector(savedSector.id, {
        agents: updatedAgents,
        sectorName: finalSectorName,
        sectorSymbol: finalSectorSymbol
      });

      if (!updatedSector) {
        throw new Error('Failed to update sector with manager agent');
      }

      return reply.status(201).send(updatedSector);
    } catch (error) {
      return reply.status(500).send({
        error: error.message
      });
    }
  });
};
